"""initial schema

Revision ID: 36713ee2fb69
Revises: 
Create Date: 2026-09-25 15:01:12.505762

Migration inicial com todo o schema da spec §4 (db-migrations).

Decisoes registradas para o revisor db-review:
- ``CREATE EXTENSION IF NOT EXISTS vector`` no inicio do upgrade (D3 §3.2):
  a coluna ``knowledge_chunks.embedding`` e ``vector(1536)`` e depende da
  extensao pgvector. Idempotente (o postgres/init.sql tambem a cria no banco
  de aplicacao; aqui garantimos para qualquer banco de teste/upgrade).
- Import de ``pgvector.sqlalchemy``: a coluna ``embedding`` usa
  ``pgvector.sqlalchemy.Vector(1536)`` (o autogenerate emite
  ``pgvector.sqlalchemy.vector.VECTOR(dim=1536)``; o import e necessario).
- Indice HNSW ``idx_chunks_embedding_hnsw`` (D3 §3.2):
  ``CREATE INDEX ... USING hnsw (embedding vector_cosine_ops)``. Nao e
  autogerado (o model nao declara indice); criado manualmente apos a tabela.
- Enums: ``native_enum=False`` (String + CHECK constraint), conforme db-models.
- Downgrade simetrico: drop do indice HNSW, drop das tabelas, drop da extensao.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '36713ee2fb69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Extensao pgvector (D3 §3.2): necessaria para a coluna vector(1536).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_owner_id'), 'users', ['owner_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('strategy', sa.Text(), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mcpServers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('knowledge', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('integrations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('shell_access', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_agents_owner_name')
    )
    op.create_index(op.f('ix_agents_owner_id'), 'agents', ['owner_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('node_id', sa.String(length=200), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('checkpoint_id', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifacts', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.Enum('approval_status', 'pending', 'approved', 'rejected', 'revised', native_enum=False, length=16), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('responded_by', sa.String(length=200), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel', sa.Enum('notification_channel', 'in-app', 'email', 'teams', 'slack', native_enum=False), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('attempted_channels', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('fallback_channel', sa.Enum('notification_channel', 'in-app', 'email', 'teams', 'slack', native_enum=False), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'node_id', 'checkpoint_id', name='uq_approval_requests_pipeline_node_checkpoint')
    )
    op.create_index(op.f('ix_approval_requests_node_id'), 'approval_requests', ['node_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_owner_id'), 'approval_requests', ['owner_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_pipeline_id'), 'approval_requests', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_run_id'), 'approval_requests', ['run_id'], unique=False)
    op.create_table('custom_tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('io', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('custom_tool_status', 'draft', 'deployed', 'archived', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_custom_tools_owner_name')
    )
    op.create_index(op.f('ix_custom_tools_owner_id'), 'custom_tools', ['owner_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('integration_type', 'github', 'azure', 'gitlab', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('integration_status', 'active', 'disabled', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_integrations_owner_name')
    )
    op.create_index(op.f('ix_integrations_owner_id'), 'integrations', ['owner_id'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.Enum('knowledge_scope', 'global', 'agent', 'pipeline', native_enum=False, length=16), nullable=False),
    sa.Column('scope_ref', sa.String(length=200), nullable=True),
    sa.Column('source', sa.Enum('knowledge_source', 'upload', 'vector-db', 'url', 'rivvn', native_enum=False), nullable=False),
    sa.Column('reference', sa.String(length=500), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('similarity_threshold', sa.Float(), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_knowledge_bases_owner_name')
    )
    op.create_index(op.f('ix_knowledge_bases_owner_id'), 'knowledge_bases', ['owner_id'], unique=False)
    op.create_table('mcp_servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('transport', sa.Enum('mcp_transport', 'stdio', 'sse', 'http', native_enum=False, length=16), nullable=False),
    sa.Column('command', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('env', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('mcp_status', 'connected', 'disconnected', 'error', native_enum=False, length=16), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_mcp_servers_owner_name')
    )
    op.create_index(op.f('ix_mcp_servers_owner_id'), 'mcp_servers', ['owner_id'], unique=False)
    op.create_table('pipelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pipeline_status', 'draft', 'running', 'paused', 'completed', 'failed', native_enum=False, length=16), nullable=False),
    sa.Column('entry_node_id', sa.UUID(), nullable=False),
    sa.Column('current_checkpoint', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_pipelines_owner_name')
    )
    op.create_index(op.f('ix_pipelines_owner_id'), 'pipelines', ['owner_id'], unique=False)
    op.create_table('rivvn_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('contract_status', sa.Enum('rivvn_contract_status', 'active', 'inactive', 'expired', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('rivvn_status', 'connected', 'disconnected', 'expired', native_enum=False, length=16), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', name='uq_rivvn_connections_owner')
    )
    op.create_index(op.f('ix_rivvn_connections_owner_id'), 'rivvn_connections', ['owner_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('skill_category', 'code', 'docs', 'infra', 'communication', 'analysis', native_enum=False, length=16), nullable=False),
    sa.Column('type', sa.Enum('skill_type', 'prompt', native_enum=False, length=16), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_integrations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_skills_owner_name')
    )
    op.create_index(op.f('ix_skills_owner_id'), 'skills', ['owner_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('source', sa.Enum('knowledge_doc_source', 'upload', 'url', native_enum=False), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('knowledge_doc_status', 'processing', 'ready', 'failed', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_knowledge_base_id'), 'knowledge_documents', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_owner_id'), 'knowledge_documents', ['owner_id'], unique=False)
    op.create_table('pipeline_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('edge_type', 'flow', 'data', native_enum=False), nullable=False),
    sa.Column('source', sa.UUID(), nullable=False),
    sa.Column('target', sa.UUID(), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_channel', sa.Enum('notification_channel', 'in-app', 'email', 'teams', 'slack', native_enum=False), nullable=True),
    sa.Column('approval_message', sa.Text(), nullable=True),
    sa.Column('data_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reject_target', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('flow', 'data')", name='ck_pipeline_edges_type'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'id', name='uq_pipeline_edges_pipeline_id')
    )
    op.create_index(op.f('ix_pipeline_edges_pipeline_id'), 'pipeline_edges', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_edges_source'), 'pipeline_edges', ['source'], unique=False)
    op.create_index(op.f('ix_pipeline_edges_target'), 'pipeline_edges', ['target'], unique=False)
    op.create_table('pipeline_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('agent_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'id', name='uq_pipeline_nodes_pipeline_id')
    )
    op.create_index(op.f('ix_pipeline_nodes_agent_id'), 'pipeline_nodes', ['agent_id'], unique=False)
    op.create_index(op.f('ix_pipeline_nodes_pipeline_id'), 'pipeline_nodes', ['pipeline_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('pipeline_run_status', 'running', 'paused', 'completed', 'failed', 'cancelled', native_enum=False), nullable=False),
    sa.Column('current_checkpoint_id', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'thread_id', name='uq_pipeline_runs_thread')
    )
    op.create_index(op.f('ix_pipeline_runs_owner_id'), 'pipeline_runs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_pipeline_id'), 'pipeline_runs', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_thread_id'), 'pipeline_runs', ['thread_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('type', sa.Enum('artifact_type', 'code', 'document', 'image', 'other', native_enum=False, length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_node_id'), 'artifacts', ['node_id'], unique=False)
    op.create_index(op.f('ix_artifacts_owner_id'), 'artifacts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_artifacts_run_id'), 'artifacts', ['run_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_knowledge_base_id'), 'knowledge_chunks', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_owner_id'), 'knowledge_chunks', ['owner_id'], unique=False)
    # Indice HNSW para busca de similaridade coseno (D3 §3.2).
    # Nao autogerado: o model nao declara indice; criado manualmente.
    op.execute(
        "CREATE INDEX idx_chunks_embedding_hnsw ON knowledge_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.create_table('run_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=200), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('checkpoint_status', 'completed', 'interrupted', 'failed', native_enum=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_checkpoints_node_id'), 'run_checkpoints', ['node_id'], unique=False)
    op.create_index(op.f('ix_run_checkpoints_owner_id'), 'run_checkpoints', ['owner_id'], unique=False)
    op.create_index(op.f('ix_run_checkpoints_pipeline_id'), 'run_checkpoints', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_run_checkpoints_run_id'), 'run_checkpoints', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop do indice HNSW antes de dropar a tabela (simetrico ao upgrade).
    op.execute("DROP INDEX IF EXISTS idx_chunks_embedding_hnsw")
    op.drop_index(op.f('ix_run_checkpoints_run_id'), table_name='run_checkpoints')
    op.drop_index(op.f('ix_run_checkpoints_pipeline_id'), table_name='run_checkpoints')
    op.drop_index(op.f('ix_run_checkpoints_owner_id'), table_name='run_checkpoints')
    op.drop_index(op.f('ix_run_checkpoints_node_id'), table_name='run_checkpoints')
    op.drop_table('run_checkpoints')
    op.drop_index(op.f('ix_knowledge_chunks_owner_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_knowledge_base_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_artifacts_run_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_owner_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_node_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_pipeline_runs_thread_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_pipeline_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_owner_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_pipeline_nodes_pipeline_id'), table_name='pipeline_nodes')
    op.drop_index(op.f('ix_pipeline_nodes_agent_id'), table_name='pipeline_nodes')
    op.drop_table('pipeline_nodes')
    op.drop_index(op.f('ix_pipeline_edges_target'), table_name='pipeline_edges')
    op.drop_index(op.f('ix_pipeline_edges_source'), table_name='pipeline_edges')
    op.drop_index(op.f('ix_pipeline_edges_pipeline_id'), table_name='pipeline_edges')
    op.drop_table('pipeline_edges')
    op.drop_index(op.f('ix_knowledge_documents_owner_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_knowledge_base_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_skills_owner_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_rivvn_connections_owner_id'), table_name='rivvn_connections')
    op.drop_table('rivvn_connections')
    op.drop_index(op.f('ix_pipelines_owner_id'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_mcp_servers_owner_id'), table_name='mcp_servers')
    op.drop_table('mcp_servers')
    op.drop_index(op.f('ix_knowledge_bases_owner_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_integrations_owner_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_custom_tools_owner_id'), table_name='custom_tools')
    op.drop_table('custom_tools')
    op.drop_index(op.f('ix_approval_requests_run_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_pipeline_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_owner_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_node_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_agents_owner_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_owner_id'), table_name='users')
    op.drop_table('users')
    # Drop da extensao pgvector (simetrico ao upgrade).
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
